version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    platform: linux/amd64 
    container_name: django_pg_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./create_vector_extension.sql:/docker-entrypoint-initdb.d/01_vector.sql
    ports:
      - "1123:5432"
    networks:
      - django_network
    restart: always

  web:
    build: .
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: /usr/local/bin/entrypoint.sh 
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - django_network
    depends_on:
      - db
    ports:
      - "8000:8000"

  redis:
    image: redis:8.2-alpine
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    depends_on:
      - db
      - web
    networks:
      - django_network

  celery1:
    build: .
    container_name: django_celery
    command: celery -A config.celery worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - django_network
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    container_name: django_celery_beat
    command: celery -A config.celery beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - django_network
    depends_on:
      - db
      - redis

networks:
  django_network:
    name: django_shared_network # [핵심] 외부에서 부를 고정 이름 설정
    driver: bridge

volumes:
  postgres_data:
  redis_data:
