# Generated by Django 5.1.14 on 2025-11-21 05:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='반려 동물 종류')),
            ],
            options={
                'verbose_name': '동물 종류',
                'verbose_name_plural': '동물 종류들',
                'db_table': 'animal_type',
            },
        ),
        migrations.CreateModel(
            name='BoardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='게시판 카테고리 이름')),
            ],
            options={
                'verbose_name': '게시판 카테고리',
                'verbose_name_plural': '게시판 카테고리 목록',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('profile_image', models.CharField(blank=True, max_length=500, null=True, verbose_name='profile image URL')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.boardcategory', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='푸들, 코숏 등', max_length=100, verbose_name='품종명')),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='core.animaltype', verbose_name='동물 종류')),
            ],
            options={
                'verbose_name': '품종',
                'verbose_name_plural': '품종들',
                'db_table': 'breed',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='core.breed', verbose_name='품종')),
            ],
            options={
                'verbose_name': '반려동물',
                'verbose_name_plural': '반려동물들',
                'db_table': 'pet',
            },
        ),
        migrations.CreateModel(
            name='PetOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='owner', help_text='owner, co-owner 등', max_length=50, verbose_name='역할')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='보호자')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pet', verbose_name='반려동물')),
            ],
            options={
                'verbose_name': '반려동물 소유권',
                'verbose_name_plural': '반려동물 소유권들',
                'db_table': 'pet_ownership',
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='owners',
            field=models.ManyToManyField(related_name='pets', through='core.PetOwnership', to=settings.AUTH_USER_MODEL, verbose_name='보호자들'),
        ),
        migrations.AddConstraint(
            model_name='breed',
            constraint=models.UniqueConstraint(fields=('animal_type', 'name'), name='unique_breed_per_animal_type'),
        ),
        migrations.AddConstraint(
            model_name='petownership',
            constraint=models.UniqueConstraint(fields=('pet', 'owner'), name='unique_pet_owner'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['breed'], name='pet_breed_i_1d5a48_idx'),
        ),
    ]
