# Generated by Django 5.1.14 on 2025-11-28 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='like_users',
            field=models.ManyToManyField(related_name='like_boards', through='core.BoardLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Shorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('video_url', models.URLField(verbose_name='비디오 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '쇼츠',
                'verbose_name_plural': '쇼츠 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortsLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shorts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shorts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shorts',
            name='like_users',
            field=models.ManyToManyField(related_name='like_shorts', through='core.ShortsLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='boardlike',
            constraint=models.UniqueConstraint(fields=('user', 'board'), name='unique_board_like'),
        ),
        migrations.AddConstraint(
            model_name='shortslike',
            constraint=models.UniqueConstraint(fields=('user', 'shorts'), name='unique_shorts_like'),
        ),
    ]
