# Generated by Django 5.1.14 on 2025-12-05 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_boardlike_board_like_users_shorts_shortslike_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="카테고리명"),
                ),
            ],
            options={
                "verbose_name": "상품 카테고리",
                "verbose_name_plural": "상품 카테고리 목록",
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="상품명")),
                ("description", models.TextField(verbose_name="상세 설명")),
                ("base_price", models.PositiveIntegerField(verbose_name="기본 가격")),
                ("is_sale", models.BooleanField(default=False, verbose_name="판매 중 여부")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="core.category",
                        verbose_name="카테고리",
                    ),
                ),
            ],
            options={
                "verbose_name": "상품",
                "verbose_name_plural": "상품 목록",
                "db_table": "product",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="예: 색상, 사이즈", max_length=50, verbose_name="옵션 종류"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="예: 블랙, L", max_length=50, verbose_name="옵션 값"
                    ),
                ),
                (
                    "additional_price",
                    models.IntegerField(default=0, verbose_name="추가 금액"),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="재고 수량")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="core.product",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "상품 옵션",
                "verbose_name_plural": "상품 옵션 목록",
                "db_table": "product_option",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "name", "value"),
                        name="unique_product_option_combination",
                    )
                ],
            },
        ),
    ]
