# Generated by Django 5.1.14 on 2025-12-05 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_category_product_productoption"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(verbose_name="이미지 URL")),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="대표 이미지 여부"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="노출 순서"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.product",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "상품 이미지",
                "verbose_name_plural": "상품 이미지 목록",
                "db_table": "product_image",
                "ordering": ["order"],
            },
        ),
    ]
