# Generated by Django 5.1.14 on 2025-12-05 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_productimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="basket",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최근 수정일"),
                ),
            ],
            options={
                "verbose_name": "장바구니",
                "verbose_name_plural": "장바구니 목록",
                "db_table": "basket",
            },
        ),
        migrations.CreateModel(
            name="BasketItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="수량")),
                (
                    "price_at_addition",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="상품 가격 변동에 대비하여 기록",
                        max_digits=10,
                        null=True,
                        verbose_name="추가 시점 가격",
                    ),
                ),
                (
                    "basket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.basket",
                        verbose_name="소속 장바구니",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.productoption",
                        verbose_name="선택된 옵션",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.product",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "장바구니 항목",
                "verbose_name_plural": "장바구니 항목 목록",
                "db_table": "basket_item",
                "unique_together": {("basket", "option")},
            },
        ),
    ]
