# Generated by Django 5.1.14 on 2025-12-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_basket_basketitem"),
    ]

    operations = [
        migrations.AlterModelTable(name="basket", table=None,),
    ]
