# Generated by Django 5.1.14 on 2025-12-13 09:50

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_basket_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='OpenAI embedding vector', null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
        migrations.AddField(
            model_name='breed',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='OpenAI embedding vector', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='OpenAI embedding vector', null=True),
        ),
        migrations.AddField(
            model_name='shorts',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
        migrations.AddField(
            model_name='shorts',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='OpenAI embedding vector', null=True),
        ),
    ]
