# Generated by Django 5.1.14 on 2025-12-13 10:42

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_board_embedding_breed_description_breed_embedding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='description',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='embedding',
        ),
        migrations.CreateModel(
            name='BreedKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='예: 성격, 털 빠짐, 주의사항, 추천 양육 환경', max_length=100, verbose_name='주제')),
                ('content', models.TextField(help_text='RAG 검색에 사용될 상세 설명', verbose_name='내용')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='OpenAI embedding vector', null=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledges', to='core.breed', verbose_name='품종')),
            ],
            options={
                'verbose_name': '품종 지식',
                'verbose_name_plural': '품종 지식들',
                'db_table': 'breed_knowledge',
            },
        ),
    ]
