# Generated by Django 5.1.14 on 2025-12-14 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_breed_description_remove_breed_embedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_uid', models.CharField(max_length=100, unique=True, verbose_name='주문 번호')),
                ('status', models.CharField(choices=[('PENDING', '결제 대기'), ('PAID', '결제 완료'), ('CANCELLED', '주문 취소'), ('FAILED', '결제 실패')], default='PENDING', max_length=20, verbose_name='주문 상태')),
                ('total_amount', models.PositiveIntegerField(verbose_name='총 결제 금액')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='주문 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='주문자')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문 목록',
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('price', models.PositiveIntegerField(help_text='구매 시점의 개당 가격', verbose_name='구매 단가')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productoption', verbose_name='옵션')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order', verbose_name='주문')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '주문 상품',
                'verbose_name_plural': '주문 상품 목록',
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imp_uid', models.CharField(blank=True, max_length=100, null=True, verbose_name='포트원 결제 고유 UID')),
                ('amount', models.PositiveIntegerField(verbose_name='결제 금액')),
                ('status', models.CharField(help_text='ready, paid, cancelled, failed 등', max_length=50, verbose_name='PG사 결제 상태')),
                ('response_json', models.JSONField(blank=True, null=True, verbose_name='PG사 응답 전문')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.order', verbose_name='주문')),
            ],
            options={
                'verbose_name': '결제 로그',
                'verbose_name_plural': '결제 로그 목록',
                'db_table': 'payment',
            },
        ),
    ]
