# Generated by Django 5.1.14 on 2025-12-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_email_chatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorts',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True, verbose_name='썸네일 URL'),
        ),
    ]
