# Generated by Django 5.1.14 on 2025-12-18 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_shorts_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('shorts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shorts', verbose_name='쇼츠')),
            ],
            options={
                'verbose_name': '쇼츠 댓글',
                'verbose_name_plural': '쇼츠 댓글 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
