# Generated by Django 5.1.14 on 2025-12-18 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_shortscomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortscomment',
            name='shorts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.shorts', verbose_name='쇼츠'),
        ),
    ]
