# Generated by Django 5.1.14 on 2025-12-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_shortscomment_shorts'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='누적 조회수'),
        ),
    ]
