# Generated by Django 5.1.14 on 2025-12-19 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_board_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardlike',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.board'),
        ),
        migrations.AlterField(
            model_name='shortslike',
            name='shorts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.shorts'),
        ),
    ]
