# Generated by Django 5.1.14 on 2025-12-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_boardlike_board_alter_shortslike_shorts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(default='free', max_length=50, verbose_name='카테고리'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BoardCategory',
        ),
    ]
