# Generated by Django 5.1.14 on 2025-12-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_user_managers_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_image_url',
            field=models.URLField(blank=True, help_text='상세 설명에 사용할 긴 이미지 주소', null=True, verbose_name='상세 이미지 URL'),
        ),
    ]
