# Generated by Django 5.1.14 on 2025-12-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_user_managers_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorts',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='shorts',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='비디오 URL'),
        ),
    ]
