# Generated by Django 5.1.14 on 2025-12-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_product_detail_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail_image_url',
            field=models.URLField(blank=True, help_text='상세 설명에 사용할 긴 이미지 주소', max_length=500, null=True, verbose_name='상세 이미지 URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=True, verbose_name='판매 중 여부'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(max_length=500, verbose_name='이미지 URL'),
        ),
    ]
