# Generated by Django 5.1.14 on 2025-12-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_shorts_title_alter_shorts_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorts',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='썸네일 URL'),
        ),
        migrations.AlterField(
            model_name='shorts',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='비디오 URL'),
        ),
    ]
