# Generated by Django 5.1.14 on 2025-12-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_shorts_thumbnail_url_alter_shorts_video_url'),
        ('core', '0020_alter_product_detail_image_url_and_more'),
    ]

    operations = [
    ]
